version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.8
    commands:
      - echo "Installing dependencies..."
      - pip install -U --upgrade pip
      - pip install -r Requirements.txt 
  build:
    commands:
      - echo "Zipping deployment package..."
      - zip -r9 ../deployment_package.zip .
      - zip -g deployment_package.zip python_function.py
  post_build:
    commands:
      - echo "Updating lambda Function..."
      - aws lambda update-function-code --function-name testsso-deregister1 --zip-file fileb://deployment_package.zip
      - echo "DONE!!"
      - echo "Add Lambda Permission..."
      - aws lambda add-permission --statement-id InvokeLambdaFunction --action lambda:InvokeFunction --principal events.amazonaws.com --function-name arn:aws:lambda:us-east-1:561880438739:function:testsso-deregister1 --source-arn arn:aws:events:us-east-1:561880438739:rule/ssmrule
      - echo "DONE!!"
