version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.8
    commands:
      - echo "Installing dependencies..."
      - pip install -U --upgrade pip
      - pip install -r Requirements.txt 
  build:
    commands:
      - echo "Zipping deployment package..."
      - zip -r9 ../deployment_package.zip .
      - zip -g deployment_package.zip python_function.py
  post_build:
    commands:
      - echo "Create lambda Function..."
      - aws lambda create-function --function-name testsso-deregister1 --role arn:aws:iam::561880438739:role/service-role/testsso-dev-role-px3w33bx --handler index.handler --runtime python3.8 --zip-file fileb://deployment_package.zip
      - echo "DONE!!"
      - echo "Add Lambda Permission..."
      - aws lambda add-permission --statement-id InvokeLambdaFunction --action lambda:InvokeFunction --principal events.amazonaws.com --function-name arn:aws:lambda:us-east-1:561880438739:function:testsso-deregister1 --source-arn "arn:aws:iam::561880438739:role/CodeBuildIAMRole"
      - echo "DONE!!"         
      - echo "Create Event Rule..."
      - aws events put-rule --name "malinitestrule" --event-pattern "{\"source\":[\"aws.ec2\"],\"detail-type\":[\"AWS API Call via CloudTrail\"],\"detail\":[\"CreateImage\"]}"  --role-arn "arn:aws:iam::561880438739:role/PipelineIAMRole"
      - echo "DONE!!"
      - echo "Create Targets..."
      - aws events put-targets --rule malinitestrule --targets "Id"="1","Arn"="arn:aws:lambda:us-east-1:561880438739:function:ssoderegistration"                  
      - echo "DONE!!"
      - echo "Create Targets..."
      - aws events put-targets --rule malinitestrule --targets "Id"="2","Arn"="arn:aws:sns:us-east-2:561880438739:ssotestsns"                  
      - echo "DONE!!"
